### ISSUE TITLE
The pretrained model for pegasus

### ISSUE THREAD

**Issue by xzm2000** [antonio-mastropaolo/robustness-copilot#2]
I am interested in this experiment, can you provide me with the pre-training model used here? Thank you~

https://github.com/antonio-mastropaolo/robustness-copilot/blob/74608f46b432c472427e56f5f2523bdbf2edc99d/Code/pre-processing/Pegasus/pegasus.py#L12

**Comment by antonio-mastropaolo** [comment]
Hi @xzm2000 

The pre-trained model we used is exactly the one you find within the quotes ```tuner007/pegasus_paraphrase```
No further fine-tuning is needed.

For the record, here ```https://huggingface.co/tuner007/pegasus_paraphrase``` you get more information about the pegasus model used in the experimentation.

**Comment by xzm2000** [comment]
Thanks, I'll take a look.
